apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/influx"
    type: DirectoryOrCreate
  claimRef:
    name: influxdb-pv-claim
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - image: influxdb_image
        name: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb
          mountPath: /var/lib/influxdb
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: influxdb
          persistentVolumeClaim:
            claimName: influxdb-pv-claim